# - name: Install Fish
#   shell: nix-env -iA nixpkgs.fish
#   tags: &tags_for_fish_tasks ["install", "productivity", "dotfiles", "fish"]
#   become_user: "{{ username }}"
- name: Install Fish
  apt: name=fish
  tags: &tags_for_fish_tasks ["install", "productivity", "dotfiles", "fish"]
  become_user: "root"
  become: true
- name: Change shell to fish
  shell: chsh -s $(which fish)
  become_user: root
#   tags: *tags_for_fish_tasks
# - name: Install starship
#   shell: nix-env -iA nixpkgs.starship
#   tags: *tags_for_fish_tasks

# - name: Setup starship
#   shell: echo 'starship init fish | source' >> ~/.config/fish/config.fish
#   tags: *tags_for_fish_tasks
