- hosts: localhost
  become: yes
  environment:
    PATH: "/nix/var/nix/profiles/default/bin/:{{ lookup('env', 'PATH') }}"
  vars:
    personal: "{{ lookup('env', 'HOME') }}/personal"
    username: solomon

  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core

  tasks:
    - import_tasks: tasks/zsh-setup.yml

